name: CI

on:
  push:
    branches: [ "feature" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Run the power shell script
        run: |
          ./test_file.ps1
        shell: pwsh
