name: Validate Terraform

on:
  push:
    branches: [ "feature" ]
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_TERRAFORM_CREDENTIALS }}
    
    - name: Validation step
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        scriptLocation: ./pwsh_scripts/validate_terraform
    
    - name: Validation step
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: az logout


