name: Validate Terraform

on:
  push:
    branches: [ "feature" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Run the validation script
        run: |
          ./pwsh_scripts/validate_terraform.ps1
        shell: pwsh
