name: Validate Terraform

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo        
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '>=1.6.5'

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Validate login
      run: az account show
      shell: pwsh
    
    - name: Validation step
      run: ./pwsh_scripts/validate_terraform.ps1
      shell: pwsh
    
    - name: Azure logout
      run: az logout
      shell: pwsh


